### ISSUE TITLE
Add checking for html tags?

### ISSUE THREAD

**Issue by pgensler** [trinker/textclean#15]
Is it possible to have check_text check for html tags in text that could cause issues? I understand that most people would probably already know about this in their data, but could be useful. As an example:
```
test <- "I will have more glassware to wash, as frankly I will likely try the same wine from a few glasses. It is highly educational!<br /><br /><b>DAY 2:</b> Still going strong. Smooth as velvet, rich, deep and integrated. Excellent!"
textclean::check_text(test)
```

**Comment by trinker** [comment]
This is an excellent idea.  I'll add in the next version of **textclean**
