### ISSUE TITLE
Support for XHTML Cleaning?

### ISSUE THREAD

**Issue by pgensler** [trinker/textclean#16]
I'm not sure if this is a task for xml2 or for text clean, but consider this string: 
I would like to remove the XHTML? tags from this, and I can easily do it with stringr, but not with replace_html. Should this be supported or am I using this function for the wrong purposes? Thanks.

```
test <- "I will have more glassware to wash, as frankly I will likely try the same wine from a few glasses. It is highly educational!<br /><br /><b>DAY 2:</b> Still going strong. Smooth as velvet, rich, deep and integrated. Excellent!"

textclean::replace_html(test,symbol = FALSE)
print(test)
```

**Comment by trinker** [comment]
I believe you think `textclean::replace_html` does assignment by reference.  This is not the case and this is true for most functions.  data.table's `:=` operator is one notable exception.  Try:

```
test <- "I will have more glassware to wash, as frankly I will likely try the same wine from a few glasses. It is highly educational!<br /><br /><b>DAY 2:</b> Still going strong. Smooth as velvet, rich, deep and integrated. Excellent!"

test <- textclean::replace_html(test,symbol = FALSE)
print(test)
```

**Comment by trinker** [comment]
@pgensler Can you let me know if this is the case so I can close this issue?

**Comment by trinker** [comment]
I'm closing this...feel free to reopen if I have not addressed it.

**Comment by pgensler** [comment]
Sorry for the late response, I am trying this on a single column, instead of a massive vector to apply the changes. I'll let you know how things turn out
