### ISSUE TITLE
Trouble with clean_text

### ISSUE THREAD

**Issue by woodbomb50** [trinker/textclean#24]
```
y <- "A valid sentence"
testFileName <- "check_test_results.txt"

check_text(y, file = testFileName)

if (!file.exists(testFileName)) {
  cat("check_text found no problems with", y, '\n')
} else {
  cat("check_text found problems with", y, '\n')
  print(testFileName)
}

===================
Result:

check_text found no problems with A valid sentence
```

**Comment by trinker** [comment]
I get:

```
check_text found problems with A valid sentence 
[1] "check_test_results.txt"
```

And in the file I get:

```
==========================
MISSING ENDING PUNCTUATION
==========================

The following observations were missing ending punctuation:

1

The following text is missing ending punctuation:

1: A valid sentence

*Suggestion: Consider cleaning the raw text or running `add_missing_endmark`
```

can you post session info?

**Comment by woodbomb50** [comment]
Tyler,

I was expecting what you swaw.

Here's sessionInfo():

################################

R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
LC_TIME=en_US.UTF-8
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
LC_ADDRESS=C
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rlist_0.4.6.1   textclean_0.3.1 stringr_1.2.0   quanteda_0.99

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12        lubridate_1.6.0     lattice_0.20-35
digest_0.6.12
 [5] grid_3.4.1          plyr_1.8.4          gtable_0.2.0
magrittr_1.5
 [9] scales_0.5.0        RcppParallel_4.3.20 ggplot2_2.2.1
rlang_0.1.2
[13] stringi_1.1.5       lazyeval_0.2.0      data.table_1.10.4
Matrix_1.2-10
[17] fastmatch_1.1-0     tools_3.4.1         hunspell_2.6
munsell_0.4.3
[21] compiler_3.4.1      colorspace_1.3-2    tibble_1.3.4

>

Roy W Wilson, Analyst

My ResearchGate Profile: https://www.researchgate.net/profile/Roy_Wilson

PhD (Social and Comparative Analysis in Education;  Minor in Quantitative
Research Methods - PITT),
MA (History and Policy - CMU), MH (Humanities - CU),
MSCS (Computer Science - DU), MA (Mathematics - DU),
BA (Mathematics and Philosophy - MSCD)

email: anw1950@gmail.com

**Comment by trinker** [comment]
Can you try installing the latest version via:

```
devtools::install_packages('trinker/textclean')
```

restart R into a vanilla session and then immediately run:

```
library(textclean)
check_text("A valid sentence")
```

**Comment by woodbomb50** [comment]
For whatever reason, trying

devtools::install_packages('trinker/textclean')

in a terminal did not work. I have not been interacting with R from within
a terminal window, using RStudio instead.

> install_packages('trinker/textclean')Error in install_packages("trinker/textclean") :
  could not find function "install_packages">


## However, doing the following within the Rstudio console seemed to
do the trick.


> install.packages("textclean")Installing package into ‘/home/roy/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)trying URL
'https://cran.rstudio.com/src/contrib/textclean_0.3.1.tar.gz'Content
type 'application/x-gzip' length 130047 bytes (126
KB)==================================================downloaded 126 KB
* installing *source* package ‘textclean’ ...** package ‘textclean’
successfully unpacked and MD5 sums checked** R** data*** moving
datasets to lazyload DB** inst** preparing package for lazy loading**
help*** installing help indices** building package indices** testing
if installed package can be loaded* DONE (textclean)The downloaded
source packages are in
	‘/tmp/Rtmp7OUt4A/downloaded_packages’> library(textclean)>
check_text("A valid sentence")
==========================
MISSING ENDING PUNCTUATION
==========================

The following observations were missing ending punctuation:

1

The following text is missing ending punctuation:

1: A valid sentence

*Suggestion: Consider cleaning the raw text or running `add_missing_endmark`


Thanks for the quick and effective response.

Do you anticipate any continuing problem? I would think not.

Roy W Wilson, Analyst

**Comment by trinker** [comment]
Excellent.  I'll close this then...PS I meant to say `devtools::install_github('trinker/textclean')
`
