### ISSUE TITLE
Error while applying mgsub if fixed = FALSE

### ISSUE THREAD

**Issue by asitemade4u** [trinker/textclean#45]
I get an error while applying `mgsub` to texts:

`
Error in gsub(pattern[i], replacement[i], x, fixed = fixed, ...) :
  assertion 'tree->num_tags == num_tags' failed in executing regexp: file 'tre-compile.c', line 634
`

Maybe I am doing something wrong. Here is my code (I use a wrapper around `mgsub`):

`
thetxt %>%
lex_txtrpl(thetxt = ., lex = lexlpc, rpl = " ")
`

(`lexlpc` is a character vector, not empty).

where `lex_txtrpl` code is:

```
lex_txtrpl <- function(thetxt = "", lex = vector(), rpl = " "){
    len <- length(lex)
    if(len > 0){
        therpl <- vector(mode = "character", length = len)
        therpl <- paste0(therpl, rpl)
        thetxt <- mgsub(thetxt, lex, therpl, fixed = F, leadspace = T, trailspace = T, order.pattern = F, trim = T)
    } else{
        print("Replacement vector is empty.")
    }
    return(thetxt)
}

```
Please note that the error is NOT triggered when `fixed = TRUE`

**Comment by trinker** [comment]
Can you provide the data you used or at the very least make this reproducible?

**Comment by trinker** [comment]
I'm closing this as no data was provided.  Feel free to reopen and provided a reproducible example.
