### ISSUE TITLE
replace_emoticon replaces xp in the middle of a word

### ISSUE THREAD

**Issue by cchalloner** [trinker/textclean#46]
The replace_emoticon function replaces “xp” with “tongue sticking out” even when “xp” is in the middle of a word.  Is there a way to “remove” some of the checks from the function?  Or make sure that only whole words are replaced?

Here’s my testing, for your reference:

```
library(textclean)

test <- c("experience", "xp")
test
## [1] "experience" "xp"        

replace_emoticon(test)
## [1] "e tongue sticking out erience" " tongue sticking out " 
```

**Comment by cchalloner** [comment]
Update - I have found the same issue with other emoticons as well, not just the one listed above.

**Comment by trinker** [comment]
Works as expected now in the dev version:

```
> test <- c("experience", "xp")
> test
[1] "experience" "xp"        
> ## [1] "experience" "xp"        
> 
> replace_emoticon(test)
[1] "experience"          "tongue sticking out"
```

Thanks for reporting.

**Comment by pverspeelt** [comment]
@trinker, 

This works, but if you have the sentence "i had a great experience xp :P" the result is "i had a great experience tongue sticking out :P". The word boundery is interfering with the last part of the regex. See this [SO question](https://stackoverflow.com/questions/62270337/replace-emoticon-function-incorrectly-replaces-characters-within-a-word-r) for more info.

Replacing the first word boundery check would solve this. 
```
replace_emoticon2 <- function(x, emoticon_dt = lexicon::hash_emoticons, ...){
  
  trimws(gsub(
    "\\s+", 
    " ", 
    mgsub_regex(x, paste0('\\Q', emoticon_dt[['x']], '\\E\\b'), paste0(" ", emoticon_dt[['y']], " "))
  ))
  
}
```
This will still have an issue if there is a word stuck to the emoticon like this: "i had a great experience xp :Pexperience", but "i had a great experiencexp:P:P" would still work.

```
    # works
    replace_emoticon2("i had a great experience xp :P")
    [1] "i had a great experience tongue sticking out tongue sticking out"
    replace_emoticon2("i had a great experiencexp:P:P")
    [1] "i had a great experience tongue sticking out tongue sticking out tongue sticking out"
     
     
    # does not work:
    replace_emoticon2("i had a great experience xp :Pnewword")
    [1] "i had a great experience tongue sticking out :Pnewword"
```

**Comment by pverspeelt** [comment]
@trinker, The new function also had an issue when there is a smiley in the text. But I created a full workaround with stringi and a regex escape function. You could also use the `mgsub` function instead of `stringi::stri_replace_all`, but I found that stringi is slightly faster.

```
replace_emoticon_new <- function (x, emoticon_dt = lexicon::hash_emoticons, ...) 
{
  regex_escape <- function(string) {
    gsub("([][{}()+*^${|\\\\?.])", "\\\\\\1", string)
  }

  stringi::stri_replace_all(x, 
                            regex = paste0("\\s+", regex_escape(emoticon_dt[["x"]])),
                            replacement = paste0(" ", emoticon_dt[['y']]),   
                            vectorize_all = FALSE)
}

test_text <- "Hello :) Great experience! xp :) :P"
replace_emoticon_new(test_text)
[1] "Hello smiley Great experience! tongue sticking out smiley tongue sticking out"
```

If you want to I can issue a PR to add this to the code base.
