### ISSUE TITLE
Handling unexpected symbol in "replace_contraction"

### ISSUE THREAD

**Issue by edenhuangSH** [trinker/textclean#47]
When some unexpected symbol shows up in `replace_contraction`, the error message of "Error: unexpected symbol in "ace contractions" would show up. Those occurrences could be ignored.

**Comment by trinker** [comment]
could you give a reproducible example?

**Comment by trinker** [comment]
@edenhuangSH can you give me a reproducibile example?

**Comment by trinker** [comment]
@edenhuangSH I ask that you provide a reproducible example.

**Comment by edenhuangSH** [comment]
Apologize for the late reply -- I wasn't able to find this problem on another example but my original dataset still had this issue... Must be the problem with my data then. I'll close this issue and sorry for the inconvenience. Thank you!
