### ISSUE TITLE
Question regarding mispelling

### ISSUE THREAD

**Issue by nghia1301** [trinker/textclean#54]
Hi, 
I am having trouble with clean my text data. I have a problem when importing pdf text, which results in wrong concatenation. For example, I have "whatismyname?" but it should be "what is my name?" Is there any way that you can help me fix this problem. I would really appreciate. I would like to use the code in R base if possible. If not, I can also use Python, but it would be my last resort. 
Thank you

**Comment by trinker** [comment]
This seems to be reading problem not a cleaning problem.   Let's go back a step.  How did you read in the data?

**Comment by nghia1301** [comment]
pdf_documents = lapply(final_pdf_df$doi, pdf_text)

this is my code for reading the data. Since I don't believe I can fix this step, I was asking how to fix misspell. Moreover, since I was seeing that there might be a[ fix](https://stackoverflow.com/questions/19675106/fixing-words-with-spaces-using-a-dictionary-look-up-in-python) in python, I thought there is 1 in R.

**Comment by trinker** [comment]
For the textclean package there is no fix.  I don't know of one in R.  If
Python has a solution, I'd go that route if you can't read it in
differently.  rticulate makes it easy to run Python code in an R session.

**Comment by nghia1301** [comment]
Thank you, sir.
